title: "@elrensmin"
email: keenignition@gmail.com
description: >-
  Work and research logs
baseurl: ""
url: "https://elrensmin.github.io"
github_username: elrensmin
twitter_username: elrensmin
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  writing:
    output: true
    permalink: /writing/:title/
  papers:
    output: true
    permalink: /papers/:title/

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: log
  - scope:
      path: ""
      type: "papers"
    values:
      layout: log
  - scope:
      path: ""
    values:
      layout: page

include:
  - .well-known

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
